success landing page complete
CityOfBoston/commissions pull request #121
Opened 2018-08-23 19:06 UTC by JOHNFLEURIMOND

2018-08-23 19:11 UTC, fionawhim requested changes

2018-08-23 19:11 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +  handler = () =>
Is this getting called?

2018-08-23 19:11 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +              fetch('http://localhost:3000/commissions/apply', {
just do `/commissions/apply` so it could work on staging

2018-08-23 19:11 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +                body: JSON.stringify({
You'll need to pass the `formData` here, right?

2018-08-23 19:11 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +                  'Content-Type': 'application/json',
If you're doing `FormData` then leave out the `Content-Type` header.

2018-10-29 14:47 UTC, paylakatel commented
This was dealt with when this project was moved to the [digital repo](https://github.com/CityOfBoston/digital)

2018-10-29 14:47 UTC, closed without merging