Checkbox complete + error message
CityOfBoston/commissions pull request #89
Opened 2018-07-23 14:27 UTC by JOHNFLEURIMOND

2018-07-23 14:36 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +              commissionIds: [''] as string[],
You should be able to replace `['']` with `['']`. Otherwise the `max` check in your validation will think there’s an extra commission checked.

2018-07-23 14:36 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +                        {errors.commissionIds}
👍

2018-07-23 14:53 UTC, finneganh commented
Is your validation of the number of checkboxes still working as expected?

2018-07-23 15:05 UTC, JOHNFLEURIMOND commented
Yes as in, an error message populates when you pass five selections saying
"Maximum of five selections only" but still can check other if they want.


On Mon, Jul 23, 2018 at 10:53 AM, Fin Hopkins <notifications@github.com>
wrote:

> Is your validation of the number of checkboxes still working as expected?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CityOfBoston/commissions/pull/89#issuecomment-407086239>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ahq0Zm9KQmw-uTBinpQ6HLd-NuxUvS3Iks5uJeNqgaJpZM4VbGHX>
> .
>

2018-07-23 15:24 UTC, fionawhim commented
I ask because the `max` is being called with `6`

2018-07-23 15:45 UTC, JOHNFLEURIMOND commented
Oh I was messing around that day. It was acting up and wasn't populating, I
fixed that.


On Mon, Jul 23, 2018 at 11:24 AM, Fin Hopkins <notifications@github.com>
wrote:

> I ask because the max is being called with 6
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CityOfBoston/commissions/pull/89#issuecomment-407097334>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ahq0Zqqag_0ZYNnc5nXoQLlkCEqHX8XNks5uJerJgaJpZM4VbGHX>
> .
>

2018-07-26 13:17 UTC, fionawhim requested changes

2018-07-26 13:17 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +                          onblur
Where is `onblur` being defined?

2018-07-26 13:17 UTC, finneganh commented on services-js/commissions-app/src/pages/commissions/apply.tsx
> +    onblur
Should be `onBlur` with a capital “B”

2018-07-26 13:50 UTC, JOHNFLEURIMOND commented
Nope, it should not. When I do every goes to poop.

On Thu, Jul 26, 2018 at 9:17 AM, Fin Hopkins <notifications@github.com>
wrote:

> *@finneganh* requested changes on this pull request.
> ------------------------------
>
> In services-js/commissions-app/src/pages/commissions/apply.tsx
> <https://github.com/CityOfBoston/commissions/pull/89#discussion_r205451213>
> :
>
> > @@ -189,31 +222,35 @@ export default class ApplyPage extends React.Component<Props> {
>                    error={touched.confirmEmail && errors.confirmEmail}
>                    onBlur={handleBlur}
>                  />
> +
> +                <FieldArray
> +                  name="commissionIds"
> +                  render={({ push, remove }) => (
> +                    <ul>
> +                      {commissions.map(commission =>
> +                        this.renderCommission(
> +                          commission,
> +                          values.commissionIds,
> +                          push,
> +                          remove,
> +                          onblur
>
> Where is onblur being defined?
> ------------------------------
>
> In services-js/commissions-app/src/pages/commissions/apply.tsx
> <https://github.com/CityOfBoston/commissions/pull/89#discussion_r205451327>
> :
>
> > @@ -20,6 +20,35 @@ export default class ApplyPage extends React.Component<Props> {
>      return { commissions };
>    }
>
> +  renderCommission(
> +    commission: Commission,
> +    checkedCommissionIds: string[],
> +    push,
> +    remove,
> +    onblur
>
> Should be onBlur with a capital “B”
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CityOfBoston/commissions/pull/89#pullrequestreview-140721819>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ahq0ZkqAqlFiyrvjmi-SMSQxYVf961fWks5uKcFzgaJpZM4VbGHX>
> .
>

2018-07-26 14:09 UTC, finneganh commented
The method argument should be called `onBlur`, regardless of what you’re passing to it.

But when you fix this up to not use `window.onblur` you won’t have the other `onblur` either.

2018-07-27 16:04 UTC, fionawhim approved these changes
LGTM!

2018-07-27 16:09 UTC, merged